name: 'GitHub CI'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-node:
    name: Test on Node.js v${{ matrix.node-version }} and jest v${{ matrix.jest-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 18.x, 19.x]
        jest-version: [27, 28, 29]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: install with jest@${{ matrix.jest-version }}
        run: yarn add --dev jest@${{ matrix.jest-version }} babel-jest@${{ matrix.jest-version }} @types/jest@${{ matrix.jest-version }}
      - run: yarn test:coverage
      - uses: codecov/codecov-action@v3
        if: ${{ always() }}

  lint:
    name: Run ESLint & TypeScript compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn build
      - run: yarn lint
      - run: yarn typecheck
